// <auto-generated />
using System;
using BookingService.Booking.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookingService.Booking.Persistence.Migrations
{
    [DbContext(typeof(BookingsContext))]
    [Migration("20250621174526_AddCatalogRequestId")]
    partial class AddCatalogRequestId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookingService.Booking.Domain.Bookings.BookingAggregate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("CatalogRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalog_request_id");

                    b.Property<DateTimeOffset>("CreationBooking")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_date_time");

                    b.Property<DateOnly>("EndBooking")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<long>("IdBooking")
                        .HasColumnType("bigint")
                        .HasColumnName("resource_id");

                    b.Property<long>("IdUser")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<DateOnly>("StartBooking")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.ToTable("bookings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
